TOPLEVEL_LANG = vhdl
TOPLEVEL = branch_unit
VHDL_SOURCES = ../../src/cpu_pkg.vhd ../../src/branch_unit.vhd
MODULE = test_branch_unit

SIM = ghdl
SIM_ARGS = --vcd=branch_unit.vcd

include $(shell cocotb-config --makefiles)/Makefile.sim
