TOPLEVEL_LANG = vhdl
TOPLEVEL = ula32_mips
VHDL_SOURCES = ../src/ula32_mips.vhd
MODULE = test_ula32_mips

SIM = ghdl
SIM_ARGS = --vcd=ula32_mips.vcd

include $(shell cocotb-config --makefiles)/Makefile.sim
